# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Bot_Response_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('context_set', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='bot_response',
            name='response_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Bot_Response_Model'),
        ),
    ]
