# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bot_Response',
            new_name='Sipintar_Response',
        ),
        migrations.RenameModel(
            old_name='Bot_Response_Model',
            new_name='Sipintar_Response_Model',
        ),
        migrations.RenameModel(
            old_name='User_Message',
            new_name='Text_Message',
        ),
    ]
